require('dotenv').config();
const express=require('express');
const cors=require('cors');
const fs2=require('fs');
const rateLimit=require('express-rate-limit');
const connectDB=require('./config/db');
const app=express();
connectDB();
app.use(cors({origin:'*'}));
app.use(express.json({limit:'10kb'}));
app.use(rateLimit({windowMs:15*60*1000,max:100}));
app.use('/api/auth',require('./routes/auth'));
app.use('/api/menu',require('./routes/menu'));
app.use('/api/orders',require('./routes/orders'));
app.get('/api/health',(req,res)=>res.json({success:true,message:'API running'}));
app.get('/',(req,res)=>{res.setHeader('Content-Type','text/html');res.send(fs2.readFileSync('C:/Users/lalit/Desktop/cafe/cafe-backend/cafe.html','utf8'));});
app.get('/cafe.html',(req,res)=>{res.setHeader('Content-Type','text/html');res.send(fs2.readFileSync('C:/Users/lalit/Desktop/cafe/cafe-backend/cafe.html','utf8'));});
app.listen(5000,()=>console.log('Server running on 5000'));
